FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y git && apt-get clean

COPY . .

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

EXPOSE 8501

# Run Flask API
CMD ["streamlit", "run", "webapp/app.py"]
